version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobbyjob_db
    volumes:
    - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    restart: on-failure
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=jobbyjob_db
      - MYSQL_PORT=3306
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      
  